[package]
name = "wisp"
version = "0.1.0"
edition = "2024"

[dependencies]
wat = "1.242.0"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
wasmtime = "21.0.2"
wit-component = "0.220.1"
wit-parser = "0.220.1"
